// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ornkykgxjpvxtftuejmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ybmt5a2d4anB2eHRmdHVlam1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMDgyMDEsImV4cCI6MjA2ODY4NDIwMX0.XZLNGVCCUithRNVoTg5bLA78o0vt0vUaQy_xiDzTjUQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});